server:
  port: 8080

aws:
  region: us-east-1

spring:
  application:
    name: application
  graphql:
    schema:
      introspection:
        enabled: true
    graphiql:
      enabled: true
      path: /graphiql
    websocket:
      path: /graphql #ws://localhost:8080/graphql

baseURL: "https://localhost/api"

management:
  datadog:
    metrics:
      export:
        enabled: false
        api-key: ${DATADOG_API_KEY}
        host-tag: ${DATADOG_HOST_TAG}
        uri: https://api.datadoghq.com
        batch-size: 1000
        step: 1m
      tags:
        application: {$spring.application.name}
        env: ${spring.profiles}
